name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master

jobs:

  call-workflow-passing-data:
    uses: ./.github/workflows/learn-reusable
    with:
      username: aparna
    secrets:
      token: ${{ secrets.TOKEN }}
